### ISSUE TITLE
SDL_sound unable to decode Ogg Vorbis file

### ISSUE THREAD

**Issue by SDLBugzilla** [icculus/SDL_sound#6] opened 2021-06-29 21:59 UTC
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Ogg Vorbis file that cannot be decoded (test.ogg, video/ogg, 2012-04-21 14:01:30 +0000, 75527 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=847)

**Reported in version:** unspecified
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2012-04-21 14:01:30 +0000, Nikos Chantziaras wrote:

> Created attachment 847
> Ogg Vorbis file that cannot be decoded
> 
> SDL_sound (current hg stable-1.0) cannot decode the attached file in whole.  A part of it is decoded, but at the wrong samplerate.  The SOUND_SAMPLEFLAG_ERROR is set in the sample, but Sound_GetError() doesn't return anything.
> 
> SDL_mixer has no problems decoding the file with Mix_LoadWAV_RW, so it's not a problem with the file.  SDL_mixer is unsuitable though, because it doesn't support partial decoding; it decodes the whole file in one go.
> 
> libvorbis 1.3.2
> libogg 1.3.0
> 
> This is a test program that demonstrates the bug:
> 
> ```c
> #include <stdio.h>
> #include <SDL_sound.h>
> 
> int main(void)
> {
>     if (SDL_Init(SDL_INIT_AUDIO) != 0) {
>         printf("SDL_Init() failed: %s\n", SDL_GetError());
>         return 1;
>     }
> 
>     if (Sound_Init() == 0) {
>         printf("Sound_Init() failed: %s\n", Sound_GetError());
>         return 1;
>     }
> 
>     SDL_RWops* rw = SDL_RWFromFile("test.ogg", "rb");
>     if (rw == 0) {
>         printf("ERROR: %s\n", SDL_GetError());
>         return 1;
>     }
> 
>     Sound_AudioInfo wantedFormat;
>     wantedFormat.channels = 2;
>     wantedFormat.rate = 44100;
>     wantedFormat.format = AUDIO_S16LSB;
> 
>     Sound_Sample* sample = Sound_NewSample(rw, "OGG", &wantedFormat, 4096);
>     if (sample == 0) {
>         printf("ERROR: %s\n", Sound_GetError());
>         return 1;
>     }
>     Sound_DecodeAll(sample);
>     if (sample->flags & SOUND_SAMPLEFLAG_ERROR) {
>         printf("ERROR: %s\n", Sound_GetError());
>     }
> 
>     Sound_Quit();
>     SDL_Quit();
>     return 0;
> }
> ```

**Comment by icculus** [comment] 2021-06-29 22:22
I haven't tested this yet, but there's a _good_ chance this has been resolved in the last nine years, by the move to stb_vorbis if nothing else.

**Comment by sezero** [comment] 2021-06-30 01:56
The 2.0 branch doesn't fail.

The stable-1.0 branch does fail
With the user's code:
```
$ ./a.out
Trying to open timidity.cfg
Trying to open /usr/local/lib/timidity/timidity.cfg
Trying to open /usr/local/share/timidity/timidity.cfg
Trying to open /usr/share/timidity/timidity.cfg
OGG: Accepting data stream.
OGG: vendor == [Xiph.Org libVorbis I 20070622].
OGG: user comment [ENCODER=XiphQT, CAVorbisEncoder.cpp $Rev: 12399 $].
OGG: bitstream version == (0).
OGG: bitstream channels == (6).
OGG: bitstream sampling rate == (22050).
OGG: seekable == {TRUE}.
OGG: number of logical bitstreams == (1).
OGG: serial number == (1710557436).
OGG: total seconds of sample == (6.138367).
Adding filter: Sound_ConvertMono
Adding filter: Sound_RateMUL2
New sample DESIRED format: S16LSB format, 44100 rate, 2 channels.
New sample ACTUAL format: S16LSB format, 22050 rate, 6 channels.
On-the-fly conversion: ENABLED.
ERROR: (null)
```
With the playsound example program:
```
$ ./playsound test.ogg 
Trying to open timidity.cfg
Trying to open /usr/local/lib/timidity/timidity.cfg
Trying to open /usr/local/share/timidity/timidity.cfg
Trying to open /usr/share/timidity/timidity.cfg
OGG: Accepting data stream.
OGG: vendor == [Xiph.Org libVorbis I 20070622].
OGG: user comment [ENCODER=XiphQT, CAVorbisEncoder.cpp $Rev: 12399 $].
OGG: bitstream version == (0).
OGG: bitstream channels == (6).
OGG: bitstream sampling rate == (22050).
OGG: seekable == {TRUE}.
OGG: number of logical bitstreams == (1).
OGG: serial number == (1710557436).
OGG: total seconds of sample == (6.138367).
New sample DESIRED format: S16LSB format, 22050 rate, 6 channels.
New sample ACTUAL format: S16LSB format, 22050 rate, 6 channels.
On-the-fly conversion: DISABLED.
Now playing [test.ogg]...
Error in decoding sound file!
  reason: [(null)].
```
Haven't traced the error.

**Comment by sezero** [comment] 2021-06-30 05:20
OK, the problem is in OGG_read() trying to read more than it could:
https://github.com/icculus/SDL_sound/blob/stable-1.0/decoders/ogg.c#L273

When I put two debug prints in there, I get this:
```
KEEP GRABBING for 13312 bytes
13312 LEFT
10240 LEFT
7168 LEFT
4096 LEFT
1024 LEFT
4 LEFT
vorbisfile.c:ov_read_filter:1997: EINVAL
```
The reason _should_ be that the file is 6 channels and we want to read 4
bytes.  If I comment out that whole block (lines 272-348), then decoding
succeeds, like:
```diff
diff --git a/decoders/ogg.c b/decoders/ogg.c
index 680118b..f3e7e55 100644
--- a/decoders/ogg.c
+++ b/decoders/ogg.c
@@ -270,6 +270,7 @@ static Uint32 OGG_read(Sound_Sample *sample)
     else if (rc < 0)
         sample->flags |= SOUND_SAMPLEFLAG_ERROR;
 
+#if 0
     /* If the buffer isn't filled, keep trying to fill it
      * until no more data can be grabbed */
     else if ((Uint32) rc < internal->buffer_size)
@@ -345,6 +346,7 @@ static Uint32 OGG_read(Sound_Sample *sample)
          */
         rc = total_bytes_read;
     }
+#endif
 
     return((Uint32) rc);
 } /* OGG_read */
```

Why is that filling in the whole buffer really necessary?

**Comment by sezero** [comment] 2021-06-30 13:58
@icculus: I can comment out that code like I suggested above, unless there is a specific reason for it.

**Comment by icculus** [comment] 2021-06-30 14:19
You're probably right, but let me look at this first.

**Comment by icculus** [comment] 2021-06-30 14:58
Ok, so filling the whole buffer is necessary (or as close to it as possible), per this comment:

```c
/* Note: According to the Vorbis documentation:
 * "ov_read() will  decode at most one vorbis packet per invocation, 
 * so the value returned will generally be less than length."
 * Due to this, for buffer sizes like 16384, SDL_Sound was always getting
 * an underfilled buffer and always setting the EAGAIN flag.
 * Since the SDL_Sound API implies that the entire buffer
 * should be filled unless EOF, additional code has been added
 * to this function to call ov_read() until the buffer is filled.
 * However, there may still be some corner cases where the buffer
 * cannot be entirely filled. So be aware.
 */
```

So it's worth clamping `bytes_remaining` in that loop to the size of a sample frame, so it drops out correctly with as much of the buffer filled as possible, without trying to read a partial frame.

That being said, the documentation on loading a sample (and also the docs on manually adjusting the decode buffer size) say this:

```c
 /* The buffer size specified must be a multiple of the size of a single
 *  sample point. So, if you want 16-bit, stereo samples, then your sample
 *  point size is (2 channels * 16 bits), or 32 bits per sample, which is four
 *  bytes. In such a case, you could specify 128 or 132 bytes for a buffer,
 *  but not 129, 130, or 131 (although in reality, you'll want to specify a
 *  MUCH larger buffer).
 * /
```

("sample point" was probably meant to say "sample frame" but there's like 17 different terms that all mean the same thing.)

Which suggests the bug is that we shouldn't be allowed to get into a situation where we decode a partial sample frame.

**Comment by sezero** [comment] 2021-06-30 19:19
I'll leave this to you then?

**Comment by icculus** [comment] 2021-06-30 19:36
> So it's worth clamping bytes_remaining in that loop to the size of a sample frame, so it drops out correctly with as much of the buffer filled as possible, without trying to read a partial frame.

This is the solution I went with; the test app is providing a correct buffer size for the format they requested, so we need to handle the actual format being uneven here.

**Closed by icculus** 2021-06-30 19:36 UTC
Labels: bug
